### ISSUE TITLE
ICP Align List Index Type Error

### ISSUE THREAD

**Issue by wyatt-ebe** [patmo141/object_alignment#11]
Python refused to run the ICP Align or ICP Align Redraw, throwing:

TypeError: list indices must be integers or slices, not float

I fixed the error and have full ICP functionality by adding an integer cast so "i = fmod(n,5)" became "i = int(fmod(n,5))"

This happened on macOS 10.14.4, Blender version 2.97b

**Comment by patmo141** [comment]
Thank you very much.  Are you interested in making more changes?  What kinds of things are you aligning?  We are about to make big changes to this repo.

**Comment by fusarino** [comment]
Hi

I really can't make the ICP work
I do not know if the code is ok or the Ike has a line to be changed. 

Thanks

**Comment by wyatt-ebe** [comment]
> Thank you very much. Are you interested in making more changes? What kinds of things are you aligning? We are about to make big changes to this repo.

I'm using the tool to align face scan meshes, in order to determine errors caused by various types of poor scans. The tool is incredibly useful, so thank you very much; I had been using an old release of MeshLab until now and the difference is staggering. 

What type of changes are you planning? I have a fairly limited background in python, so I'm not entirely sure I'd be much help in terms of extending or improving any of the alignment algorithm itself, but I'll certainly keep testing the tool as I use it, and I'll look into anything I find.

**Comment by patmo141** [comment]
We are going to make a massive improvement in UI and masking tools and prep
for 2.8 compatibility.  If you are new/limited to python this might not be
best first project but you should follow along.  I appreciate the bug fix!

**Comment by patmo141** [comment]
Hi wyatt, I forgot to push the changes I made (your changes).  We are starting to update this module to 2.80, also clean it up a bit etc.  Thank you again for your report.
