### ISSUE TITLE
'Raw floating point encoding' from stackoverflow

### ISSUE THREAD

**Issue by apollo6** [patmo141/object_alignment#12]
@patmo141 Hi.You did a fantastic work for the object alignment. I found your article at stackoverflow at 2012. It's a old article. The link is here:
   https://stackoverflow.com/questions/9403762/raw-floating-point-encoding
   I met the same problem too. When I decode the base64 data, I got the vertex data like 'a0a8f9cd20d251280bcc1' and the face data like '04000000000000000'. It's hard to move to the next. Would you please give me some advice. Thanks.

**Comment by patmo141** [comment]
please email me direclty, and I can understand more of what you are doing.  patrick dot moore dot bu at gmail dot com
