### ISSUE TITLE
I have a problem when I click Align:Picked Points

### ISSUE THREAD

**Issue by HuiProject** [patmo141/object_alignment#13]
![捕获](https://user-images.githubusercontent.com/22783500/64010779-0945cb00-cb4d-11e9-9b4f-d7eccdf02da2.PNG)
![捕获2](https://user-images.githubusercontent.com/22783500/64010780-0945cb00-cb4d-11e9-9350-3b4afc48ae89.PNG)

**Comment by patmo141** [comment]
I have not update to the 2.8 API
However it is time that I do!!

Best,
P

**Comment by patmo141** [comment]
you will find now in the b_280 branch that wen you click "align picked points" you no longer get an error.  You will not see any poings being drawn on the screen, but if you click they are there, and the functionality works.  The ICP align also works now.  More to come.  Thanks for the push!
