### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by foobarbecue** [patmo141/object_alignment#4]
Hey, I'd like to cite object_alignment in a paper. Wanna use [zenodo](https://guides.github.com/activities/citable-code/) or something to get a DOI for it?

**Comment by patmo141** [comment]
Oh cool.  Sure what do I need to do?

Best,
Patrick

**Comment by patmo141** [comment]
Ok, I read the instructions, I'll do it tonight!

Best,
Patrick

**Comment by patmo141** [comment]
[![DOI](https://zenodo.org/badge/18555/patmo141/object_alignment.svg)](https://zenodo.org/badge/latestdoi/18555/patmo141/object_alignment)

**Comment by kallitokaco** [comment]
Thank you for your nice work, I used it to align mandibles and it worked well. Could you change your zenodo entry to your real name and add the co-authors(Christoph Gohlke, Nghia Ho) please? citing a pseudonym is not that professional ;)

thank you

**Comment by patmo141** [comment]
Oh my real name is not on there!?  Ha ha, ok I'll look into it tonight.

**Comment by kallitokaco** [comment]
At least it is not your name in the bibtex export:

@misc{patmo141_2015_31462,
  author       = {patmo141 and
                  Aaron Curtis},
  title        = {object_alignment: Release Preview 2},
  month        = sep,
  year         = 2015,
  doi          = {10.5281/zenodo.31462},
  url          = {http://dx.doi.org/10.5281/zenodo.31462}
}

Very nice!

**Comment by patmo141** [comment]
I finally did it!

https://zenodo.org/record/3382818#.XWqJZShKiUk

citation added in commit d48540f3e5e0da669102cdf18ecb56f4fafa6645
