### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by Guisan** [patmo141/object_alignment#5]
Hi Patrick.
I've installed the latest version of the add-on but unfortunately it doesn't appear anything in tools.
![screenshot 108](https://cloud.githubusercontent.com/assets/17667365/16452330/2285ca32-3e08-11e6-8a52-60317ee79109.jpg)

**Comment by patmo141** [comment]
check console for errors.  Strange that it is visible in user preferences but not in the toolbar.

-P

**Comment by Guisan** [comment]
Here's the console.
![screenshot 109](https://cloud.githubusercontent.com/assets/17667365/16487159/568dc3e0-3ec9-11e6-8e81-edeb3a80b2ac.png)
Guido

**Comment by patmo141** [comment]
Rename the folder 'object_alignment'

**Comment by Guisan** [comment]
I've renamed the folder and it logically works!
Thanks!
