### ISSUE TITLE
doc missing

### ISSUE THREAD

**Issue by fsmMLK** [patmo141/object_alignment#9]
Hi,

first of all, congratulations for this plugin. 

Is is possible to include some short documentation on the parameters?
Specifically I´d like to know exactly what RIGID/ROT_LOC_SCALE do.
Does ROT_LOC_SCALE indicates that one of the meshes is also allowed to scale in addition to rotate and translate in space? would it stretch the mesh? is the scaling the same in x,y and z?

Thanks.

**Comment by fsmMLK** [comment]
I would like to cite your work in a scientific paper, but for that I would need information about the algorithms you used. Do you have a couple of references you used?

Thanks and excellent work!

**Comment by patmo141** [comment]
Hi, I have now added "citation.txt" to the repository, including original works, code modules that I leveraged etc.

I think this should be fine.
"Object Alignment Addon: Implementation of ICP in Blender"
Patrick Moore et al. or you can list the other authors

I have update the zenodo listing
https://zenodo.org/record/3382818#.XWu2AShKiUl

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.3382818.svg)](https://doi.org/10.5281/zenodo.3382818)
